### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by joffreychu** [glebovpavel/IR_to_MSExcel#11]
Hello Pavel,

I try to install your plugin on a Database as a service.

I have downloaded the package IR_to_MSEExcel.
I have uploaded the script "install_all_packages.sql" with the browser on apex and run it.
But I have compilation errors on the package IR_TO_MSEXCEL.

I did the same operation on a trial on apex.oracle.com and I have the same errors.

Do you know where is my mistake ?

Thanks for your help
Joffrey

![ir_to_excel](https://cloud.githubusercontent.com/assets/1315354/13887615/075c298e-ed3d-11e5-93dc-eccb981ace4e.png)

![results_on_apex](https://cloud.githubusercontent.com/assets/1315354/13887685/6b07470c-ed3d-11e5-98b6-fcfdd8a31bb4.png)

**Comment by glebovpavel** [comment]
Hi Joffrey,

Looks so, that you use penultimate version, not last. 
Please try latest version form github, that  should work...

regards
Pavel

**Comment by ma-schroeder** [comment]
Hi Pavel,

i think the order of the packages in the install_all_packages.sql script needs to be changed. I get an installation error when using the file on apex.oracle.com, too:

![sql_script_2016-03-21_08h56_56](https://cloud.githubusercontent.com/assets/11662301/13913029/566ac492-ef43-11e5-86c2-e8cee3dd0e6b.jpg)

But after that i am able to compile the package IR_TO_MSEXCEL succesfully. This package uses xml_to_xslx.get_max_rows and XML_TO_XSLX.download_file which are created later.

regards,
Mathias

**Comment by joffreychu** [comment]
Hi Pavel,

I have downloaded the last version from github and it works now. 

Thanks a lot,
Joffrey
