### ISSUE TITLE
Is there any Restriction or different steps when user Oracle XE 11g?

### ISSUE THREAD

**Issue by castrogeneris** [glebovpavel/IR_to_MSExcel#12]
After clicking on Download i get an apex error:

![image](https://cloud.githubusercontent.com/assets/8144282/14375372/fce17220-fd1d-11e5-8c6b-de404d6d1d97.png)

I follow instruction both in Oracle XE 11g and 12c, the second one worked smooth.

Just in case, The APEX Version where it DID NOT work is 5.0.2 and where it WORKED is 5.0.0

Thanks

**Comment by castrogeneris** [comment]
I have solved my issue:

I granted execute on UTL_FILE to the schema and then recompile AS_ZIP package and BODY.

**Comment by glebovpavel** [comment]
Thank you for using this plugin.

I added AUTHID CURRENT_USER to packages, so now you can be flexible and place plugin-packages in different schemes.
