### ISSUE TITLE
Error exporting xlsx when column include Time-stamp

### ISSUE THREAD

**Issue by kylerong** [glebovpavel/IR_to_MSExcel#17]
Error exporting xlsx when column include Time-stamp eg:(08-NOV-16 05.42.40.889000 PM).

Error in PLSQL code raised during plug-in processing.

ORA-20001: ORA-01858: a non-numeric character was found where a numeric was expected ORA-06512: at "HUAWEI.IR_TO_XML", line 569 ORA-06512: at "HUAWEI.IR_TO_XML", line 663 ORA-06512: at "HUAWEI.IR_TO_XML", line 1029 ORA-06512: at "HUAWEI.IR_TO_XML", line 1055 ORA-06512: at "HUAWEI.IR_TO_XML", line 1186 ORA-06512: at "HUAWEI.XML_TO_XSLX", line 850 ORA-06512: at "HUAWEI.IR_TO_MSEXCEL", line 146

Technical Info (only visible for developers)
is_internal_error: true
apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
ora_sqlcode: -20001
ora_sqlerrm: ORA-20001: ORA-01858: a non-numeric character was found where a numeric was expected ORA-06512: at "HUAWEI.IR_TO_XML", line 569 ORA-06512: at "HUAWEI.IR_TO_XML", line 663 ORA-06512: at "HUAWEI.IR_TO_XML", line 1029 ORA-06512: at "HUAWEI.IR_TO_XML", line 1055 ORA-06512: at "HUAWEI.IR_TO_XML", line 1186 ORA-06512: at "HUAWEI.XML_TO_XSLX", line 850 ORA-06512: at "HUAWEI.IR_TO_MSEXCEL", line 146
component.type: APEX_APPLICATION_PAGE_DA_ACTS
component.id: 18424011190480324
component.name: PLUGIN_AT.FRT.GPV_IR_TO_MSEXCEL
error_backtrace:
ORA-06512: at "HUAWEI.IR_TO_MSEXCEL", line 183
ORA-06512: at line 4
ORA-06512: at "SYS.DBMS_SYS_SQL", line 1926
ORA-06512: at "SYS.WWV_DBMS_SQL", line 1033
ORA-06512: at "SYS.WWV_DBMS_SQL", line 1047
ORA-06512: at "APEX_050000.WWV_FLOW_DYNAMIC_EXEC", line 895
ORA-06512: at "APEX_050000.WWV_FLOW_PLUGIN", line 1209
error_statement:
begin declare

begin
wwv_flow_plugin_api.g_dynamic_action_ajax_result := IR_TO_MSEXCEL.ajax (p_dynamic_action => wwv_flow_plugin_api.g_dynamic_action,p_plugin => wwv_flow_plugin_api.g_plugin );end;
end;

**Comment by kylerong** [comment]
Another error for exporting xlsx

Error in PLSQL code raised during plug-in processing.

ORA-20001: ORA-01858: a non-numeric character was found where a numeric was expected ORA-06512: at "HUAWEI.IR_TO_XML", line 569 ORA-06512: at "HUAWEI.IR_TO_XML", line 663 ORA-06512: at "HUAWEI.IR_TO_XML", line 1029 ORA-06512: at "HUAWEI.IR_TO_XML", line 1055 ORA-06512: at "HUAWEI.IR_TO_XML", line 1186 ORA-06512: at "HUAWEI.XML_TO_XSLX", line 850 ORA-06512: at "HUAWEI.IR_TO_MSEXCEL", line 146

Technical Info (only visible for developers)
is_internal_error: true
apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
ora_sqlcode: -20001
ora_sqlerrm: ORA-20001: ORA-01858: a non-numeric character was found where a numeric was expected ORA-06512: at "HUAWEI.IR_TO_XML", line 569 ORA-06512: at "HUAWEI.IR_TO_XML", line 663 ORA-06512: at "HUAWEI.IR_TO_XML", line 1029 ORA-06512: at "HUAWEI.IR_TO_XML", line 1055 ORA-06512: at "HUAWEI.IR_TO_XML", line 1186 ORA-06512: at "HUAWEI.XML_TO_XSLX", line 850 ORA-06512: at "HUAWEI.IR_TO_MSEXCEL", line 146
component.type: APEX_APPLICATION_PAGE_DA_ACTS
component.id: 18424011190480324
component.name: PLUGIN_AT.FRT.GPV_IR_TO_MSEXCEL
error_backtrace:
ORA-06512: at "HUAWEI.IR_TO_MSEXCEL", line 183
ORA-06512: at line 4
ORA-06512: at "SYS.DBMS_SYS_SQL", line 1926
ORA-06512: at "SYS.WWV_DBMS_SQL", line 1033
ORA-06512: at "SYS.WWV_DBMS_SQL", line 1047
ORA-06512: at "APEX_050000.WWV_FLOW_DYNAMIC_EXEC", line 895
ORA-06512: at "APEX_050000.WWV_FLOW_PLUGIN", line 1209
error_statement:
begin declare

begin
wwv_flow_plugin_api.g_dynamic_action_ajax_result := IR_TO_MSEXCEL.ajax (p_dynamic_action => wwv_flow_plugin_api.g_dynamic_action,p_plugin => wwv_flow_plugin_api.g_plugin );end;
end;

**Comment by kylerong** [comment]
Another error IR contains about 2000 rows and 81 columns.

Error in PLSQL code raised during plug-in processing.

ORA-20001: ORA-04031: unable to allocate 1032 bytes of shared memory ("large pool","unknown object","qmxlu subheap","qmemNextBuf:alloc") ORA-06512: at "HUAWEI.XML_TO_XSLX", line 661 ORA-06512: at "HUAWEI.XML_TO_XSLX", line 859 ORA-06512: at "HUAWEI.IR_TO_MSEXCEL", line 146

Technical Info (only visible for developers)
is_internal_error: true
apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
ora_sqlcode: -20001
ora_sqlerrm: ORA-20001: ORA-04031: unable to allocate 1032 bytes of shared memory ("large pool","unknown object","qmxlu subheap","qmemNextBuf:alloc") ORA-06512: at "HUAWEI.XML_TO_XSLX", line 661 ORA-06512: at "HUAWEI.XML_TO_XSLX", line 859 ORA-06512: at "HUAWEI.IR_TO_MSEXCEL", line 146
component.type: APEX_APPLICATION_PAGE_DA_ACTS
component.id: 18424011190480324
component.name: PLUGIN_AT.FRT.GPV_IR_TO_MSEXCEL
error_backtrace:
ORA-06512: at "HUAWEI.IR_TO_MSEXCEL", line 183
ORA-06512: at line 4
ORA-06512: at "SYS.DBMS_SYS_SQL", line 1926
ORA-06512: at "SYS.WWV_DBMS_SQL", line 1033
ORA-06512: at "SYS.WWV_DBMS_SQL", line 1047
ORA-06512: at "APEX_050000.WWV_FLOW_DYNAMIC_EXEC", line 895
ORA-06512: at "APEX_050000.WWV_FLOW_PLUGIN", line 1209
error_statement:
begin declare

begin
wwv_flow_plugin_api.g_dynamic_action_ajax_result := IR_TO_MSEXCEL.ajax (p_dynamic_action => wwv_flow_plugin_api.g_dynamic_action,p_plugin => wwv_flow_plugin_api.g_plugin );end;
end;

**Comment by glebovpavel** [comment]
Fixed in  2.10
