### ISSUE TITLE
Unable to implement XLSX download option

### ISSUE THREAD

**Issue by JHQC** [glebovpavel/IR_to_MSExcel#20]
Hi Pavel,
By going through the steps **exactly** as described in the manual, we are not succeeding in installing the XLSX download option: XLSX doesn't appear as an option in the dropdown menu for downloads. Also, we can't get the manual download button for XLSX to appear/work. Do you know what might be causing this?

**Comment by glebovpavel** [comment]
Hi,
which version of APEX do you using? Are there any javascript errors in browser console (F12 to open it)?

**Comment by JHQC** [comment]
Hi Pavel,

Thanks for your quick reply. The version of the APEX is:

Product Build: 5.0.0.00.31
Schema Compatibility: 2013.01.01
APEX Listener Version: 3.0.4.56.18.12

Are on of these the right details for the version?

And if I look at the Javascript console I see these errors:

IR2MSEXCEL.js Failed to load resource: the server responded with a status of 404 (Not Found)
f?p=101:1:10774360895105::::::203 Uncaught ReferenceError: excel_gpv is not defined
    at f?p=101:1:10774360895105::::::203
    at HTMLDocument.<anonymous> (f?p=101:1:10774360895105::::::203)
    at j (jquery-2.1.3.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.1.3.min.js:2)
    at Function.ready (jquery-2.1.3.min.js:2)
    at HTMLDocument.I (jquery-2.1.3.min.js:2)


Met vriendelijke groet,

[1483348087559_OutlookEmoji-1469702033388_PastedImage.png]
Jeffrey Hasenbos | Business Intelligence Consultant

Phone: +31 84 876 25 89 | Mobile: +31 (0)657886734
Qcompany Oracle Business Partner

Asterweg 20L-2  Amsterdam

**Comment by glebovpavel** [comment]
Hi Jeffrey,
Looks like IR2MSEXCEL.js failed.  Can you try to reinstall APEX plugin (dynamic_action_plugin_at_frt_gpv_ir_to_msexcel.sql, 30225 bytes) ? 

Regards,
Pavel

**Comment by JHQC** [comment]
Hi Pavel,

Thanks for your quick reply! I have removed the plugin and added again. All the files have I downloaded again from the github. Unfortunately, I keep the same error messages. After page 7 of the manual you can see the button, right? I just do not see the button. Even if I manually add a button with the excel download action, he will not do that.

In the Javascript, I still have the same errors.

**Comment by glebovpavel** [comment]
Hi Jeffrey,

Very strange situation. Looks like APEX can't get access to the IR2MSEXCEL.js. Now i have no access 
to APEX 5.0, but later i make a very simple sample app that works 100% by me,  and you can compare the implementation. 

Regards,
Pavel

**Comment by glebovpavel** [comment]
Hi Jeffrey, 
Simple application is done. 

You can find it in my last commit. 
I hope, it helps you. 
 
Regards,
Pavel

**Comment by JHQC** [comment]
Hi Pavel,

Thanks for the quick reply!

Should I only run the new application in a query window? Can you explain in a few steps how your simple application works? And what are the steps to follow?

When I create a script, with your new code, in SQL Scripts I will get the following error, see these links:

[http://imgur.com/TiPQmEx](url)
[http://imgur.com/jz2z2bK](url)
[http://imgur.com/KCBvt6V](url)

Kind Regards

**Comment by glebovpavel** [comment]
Video how to export and import APEX applications (import started with 3:40)
https://www.youtube.com/watch?v=MasRJOjswqs

**Comment by JHQC** [comment]
Hi Pavel,

It works with the new commit you made! Great! Many Thanks!!
