### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by MarkusA380** [glebovpavel/IR_to_MSExcel#22]
[Screenshot of Error](https://i.stack.imgur.com/8RVMZ.png)

I have been careful to stick to the manual, but I was unable to resolve this error.
It seems that it is a bug or some kind of incompatibility.

Oracle Version: 11G
Apex Version: 5.1

**Comment by glebovpavel** [comment]
Hi Markus, 

Please check that AS_ZIP package is correct installed without errors.

**Comment by MarkusA380** [comment]
I have installed the package using the install_all_packages.sql script. How am I able to check the integrity of a single component?

**Comment by MarkusA380** [comment]
I have also tried an older version of the package, because your last commit stated "Adaptation to Apex 5.0", but I use Apex 5.1. Sadly, the error persisted.

**Comment by MarkusA380** [comment]
Hello, I am still stuck on this issue. Is there any way you could help?

**Comment by glebovpavel** [comment]
Hi Markus, 

if you really do not have any errors after install_all_packages.sql script, i can be more difficult as i thought.
Probably any security restrictions or any grants absent.

You can try add  "AUTHID CURRENT_USER"  into package AS_ZIP definition:

CREATE OR REPLACE PACKAGE  AS_ZIP 
  AUTHID CURRENT_USER
is 

  type file_list is table of clob; 
-- 
  function file2blob 
    ( p_dir varchar2 
    , p_file_name varchar2 
    ) 
  return blob; 
-- 
  function get_file_list 
    ( p_dir varchar2 
    , p_zip_file varchar2 
    , p_encoding varchar2 := null 
    ) 
  return file_list; 
-- 
  function get_file_list 
    ( p_zipped_blob blob 
    , p_encoding varchar2 := null 
    ) 
  return file_list; 
-- 
  function get_file 
    ( p_dir varchar2 
    , p_zip_file varchar2 
    , p_file_name varchar2 
    , p_encoding varchar2 := null 
    ) 
  return blob; 
-- 
  function get_file 
    ( p_zipped_blob blob 
    , p_file_name varchar2 
    , p_encoding varchar2 := null 
    ) 
  return blob; 
-- 
  procedure add1file 
    ( p_zipped_blob in out blob 
    , p_name varchar2 
    , p_content blob 
    ); 
-- 
  procedure finish_zip( p_zipped_blob in out blob ); 
-- 
  procedure save_zip 
    ( p_zipped_blob blob 
    , p_dir varchar2 := 'MY_DIR' 
    , p_filename varchar2 := 'my.zip' 
    ); 
-- 
end;
/

**Comment by MarkusA380** [comment]
Hello,

i tried your suggested change, with no different result.

I have found one rather weird issue, that is the following before running install_all_packages.sql:

```
Line Number | Unknown Statement
1 |  
```

Is that normal?

**Comment by MarkusA380** [comment]
Also,
`CREATE OR REPLACE PACKAGE  "AS_ZIP" `
is written instead of
`CREATE OR REPLACE PACKAGE  AS_ZIP`

Could that be an issue?

**Comment by glebovpavel** [comment]
Yes, it's normal.
No, "AS_ZIP" in this case is equal AS_ZIP.

Looks like for same reasons APEX can not execute function from AS_ZIP package in runtime.
If you have a test-system, you can try 

grant execute on AS_ZIP to public;

**Comment by MarkusA380** [comment]
Could you explain where and when to execute this?

**Comment by glebovpavel** [comment]
For example, in SQLPlus, but it would much safely to ask your DBA to do that.

**Comment by MarkusA380** [comment]
Don't worry, it's a test environment.

**Comment by MarkusA380** [comment]
I found out that compilation errors aren't shown when running the script "install_all_packages.sql", but instead are shown in the Object Browser of the SQL Workshop when recompiling the packages.
This way I found this error: _identifier UTIL_FILE must be declared_
So, I executed `GRANT EXECUTE ON SYS.utl_file TO PUBLIC;` on the sysdba.
This way, I could resolve the error.
