### ISSUE TITLE
not ir_to_msexcel.is_ir2msexcel  problem

### ISSUE THREAD

**Issue by damirko28** [glebovpavel/IR_to_MSExcel#27]
Hi Pavel,
excellent work. I have problem with exclude column ( use "not ir_to_msexcel.is_ir2msexcel").
Apex 5.1.2, Oracle 12c.

**Comment by glebovpavel** [comment]
Hi Damir,

thank you for using this plugin. 

Could you please give a detailed problem description, error code or explanation ....

Regards,
Pavel

**Comment by damirko28** [comment]
Hi Pavel,



Congratulations on improving performance (and I was pleased before)

Excuse me on my question without further explanation.


I forgot to mention that I'm using yours plugin from the first version.

I'm sending you Word document with an explanation of the problem.

Main message: Apex 5.1 (5.1.2 and 5.1.3) has problem with rendering column
with

*not ir_to_msexcel.is_ir2msexcel *


Regards,
Damir




2017-11-30 15:19 GMT+01:00 Pavel Glebov <notifications@github.com>:

**Comment by glebovpavel** [comment]
Hi Damir,

Thank you for very detailed explanation! 
There was a bag in version 2.20.

Fixed in 2.21

Regards,
Pavel

**Comment by damirko28** [comment]
Hi Pavel,

Thank you very much for your efforts.

I'm constantly showing yours works to my friends.

Regards,
Damir
