### ISSUE TITLE
Unable to get XLSX as Download Option

### ISSUE THREAD

**Issue by amitdesai79** [glebovpavel/IR_to_MSExcel#28]
Hello Pavel,

We are trying to use the plugin to download the report in XLSX.
We followed all the steps listed in instructions document.
1. When we run the install_all_packages,sql, we observe that only 8 packages are installed as supposed to 10 (mentioned in the instruction document).
2. When we try to run the report, we get 404 Error for the IR2MSExcel.js
The report is trying to download the IR2MSEXCEL.JS file from the following location :-
/ords/njiisrpts/static-files-not-configured/114/files/plugin/53553819074395835829/v15/IR2MSEXCEL.js

We are not sure how the path is being generated? 

Environment detail is as follows 
Oracle Application Express 5.1.2.00.09 

We have tried uninstalling and reinstalling the plugin multiple times.

Any help on this matter is greatly appreciated.

Please do let us know if any information is required.

Thank you,
Amit

**Comment by glebovpavel** [comment]
Hi Amit,

sorry for delay, i was away.

1. There is an error in documentation, old screenshots. now plugin have 4 packages (4 header + 4 body = 8), so, your results are correct.
2. Regarding this issue i found an article 
https://ora-00001.blogspot.co.at/2016/12/apex-plugin-files-and-404-not-found-in-ords.html

On my local VM i get a path http://localhost:8080/ords/plugin/r/200/files/plugin/53547601452765754881/v15/IR2MSEXCEL.js 
for the plugin installed in application 200.

Could you please write a short message, if actions described in (2)  helps you.

Regards,
Pavel

**Comment by glebovpavel** [comment]
Should be already fixed
