### ISSUE TITLE
Application Express 5.0.4.00.12 with V2 GPV Interactive Report to MSExcel

### ISSUE THREAD

**Issue by LXSysadmin** [glebovpavel/IR_to_MSExcel#30]
Hello!     
After adding Dynamic Action and running application i get error: 

is_internal_error: true
    apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
    ora_sqlcode: -4063
    ora_sqlerrm: ORA-04063: package body "XXX.IR_TO_MSEXCEL" has errors ORA-06508: PL/SQL: could not find program unit being called: "XXX.IR_TO_MSEXCEL"
    component.type: APEX_APPLICATION_PAGE_DA_ACTS
    component.id: 2904515986526014
    component.name: PLUGIN_AT.FRT.GPV_IR_TO_MSEXCEL
    error_backtrace:

    ORA-06512: at line 4
    ORA-06512: at "SYS.DBMS_SYS_SQL", line 1926
    ORA-06512: at "SYS.WWV_DBMS_SQL", line 1033
    ORA-06512: at "SYS.WWV_DBMS_SQL", line 1047
    ORA-06512: at "APEX_050000.WWV_FLOW_DYNAMIC_EXEC", line 895
    ORA-06512: at "APEX_050000.WWV_FLOW_PLUGIN", line 1209

    error_statement:

    begin declare

    begin
    wwv_flow_plugin_api.g_dynamic_action_render_result := IR_TO_MSEXCEL.render (p_dynamic_action => wwv_flow_plugin_api.g_dynamic_action,p_plugin => wwv_flow_plugin_api.g_plugin );end;
    end;

**Comment by glebovpavel** [comment]
Hi, 

could  you please grant execute on  XXX.IR_TO_MSEXCEL to the schema listed as "Parsing Schema" for you application?

Probably missing grants are the cause of this error.

Regards,
Pavel

**Comment by glebovpavel** [comment]
Should be already fixed
