### ISSUE TITLE
Error in PLSQL code raised during plug-in processing

### ISSUE THREAD

**Issue by HendriX99** [glebovpavel/IR_to_MSExcel#31]
Hi,
I successfully ran the installation script, and configured the plugin, but after clicking download-->XLSX the following error appears (Oracle Express Edition with Apex 5.1 latest version):

``
Error in PLSQL code raised during plug-in processing.

ORA-20001: ORA-06508: PL/SQL: could not find program unit being called ORA-06512: at "SALESREP.IR_TO_XLSX", line 2036 ORA-06512: at "SALESREP.IR_TO_MSEXCEL", line 158

Technical Info (only visible for developers)
is_internal_error: true
apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
ora_sqlcode: -20001
ora_sqlerrm: ORA-20001: ORA-06508: PL/SQL: could not find program unit being called ORA-06512: at "SALESREP.IR_TO_XLSX", line 2036 ORA-06512: at "SALESREP.IR_TO_MSEXCEL", line 158
component.type: APEX_APPLICATION_PAGE_DA_ACTS
component.id: 2680099305060308
component.name: PLUGIN_AT.FRT.GPV_IR_TO_MSEXCEL
error_backtrace:
ORA-06512: at "SALESREP.IR_TO_MSEXCEL", line 179
ORA-06512: at line 4
ORA-06512: at "SYS.DBMS_SQL", line 1825
ORA-06512: at "APEX_050100.WWV_FLOW_DYNAMIC_EXEC", line 1880
ORA-06512: at "APEX_050100.WWV_FLOW_DYNAMIC_EXEC", line 1895
ORA-06512: at "APEX_050100.WWV_FLOW_DYNAMIC_EXEC", line 936
ORA-06512: at "APEX_050100.WWV_FLOW_PLUGIN", line 1330
error_statement:
begin declare

begin
wwv_flow_plugin_api.g_dynamic_action_ajax_result := IR_TO_MSEXCEL.ajax (p_dynamic_action => wwv_flow_plugin_api.g_dynamic_action,p_plugin => wwv_flow_plugin_api.g_plugin );end;
end;
``
did I miss something?

thanks for your help

regards

Gennaro

**Comment by glebovpavel** [comment]
Hi Gennaro,

could you please try to grant 

GRANT EXECUTE ON SYS.DBMS_LOB TO #USER#;

Where #USER# should be replaced to APEX Application Parsing Schema.

That should help.

Regards,
Pavel

**Comment by HendriX99** [comment]
Hi,
thanks, I successfully granted the permission but the problem is still present.

As additional info, please note that I have two different interactive reports  on the same page, and I am trying to use your plugin with one of this report

best regards (and belated happy new year...)

**Comment by glebovpavel** [comment]
Hi Gennaro,

could you please additionally try to grant

GRANT EXECUTE ON IR_TO_MSEXCEL TO #USER#;
GRANT EXECUTE ON IR_TO_XLSX TO #USER#;

Where #USER# should be replaced to APEX Application Parsing Schema.

Regards,
Pavel

**Comment by JoseLiosCheng** [comment]
Hi Pavel 
I have a similar error

Error in PLSQL code raised during plug-in processing.
ORA-20001: ORA-20001: get_query_column_list: ORA-00942: la tabla o vista no existe ORA-06512: en "AGRICOLA.IR_TO_XML", línea 502 ORA-06512: en "AGRICOLA.IR_TO_XML", línea 1129 ORA-06512: en "AGRICOLA.XML_TO_XSLX", línea 849 ORA-06512: en "AGRICOLA.IR_TO_MSEXCEL", línea 124

Technical Info (only visible for developers)
is_internal_error: true
apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
ora_sqlcode: -20001
ora_sqlerrm: ORA-20001: ORA-20001: get_query_column_list: ORA-00942: la tabla o vista no existe ORA-06512: en "AGRICOLA.IR_TO_XML", línea 502 ORA-06512: en "AGRICOLA.IR_TO_XML", línea 1129 ORA-06512: en "AGRICOLA.XML_TO_XSLX", línea 849 ORA-06512: en "AGRICOLA.IR_TO_MSEXCEL", línea 124
component.type: APEX_APPLICATION_PAGE_DA_ACTS
component.id: 36014965100245012
component.name: PLUGIN_AT.FRT.GPV_IR_TO_MSEXCEL
error_backtrace:
ORA-06512: en "AGRICOLA.IR_TO_MSEXCEL", línea 161
ORA-06512: en línea 4
ORA-06512: en "SYS.DBMS_SQL", línea 1825
ORA-06512: en "APEX_050100.WWV_FLOW_DYNAMIC_EXEC", línea 1879
ORA-06512: en "APEX_050100.WWV_FLOW_DYNAMIC_EXEC", línea 1894
ORA-06512: en "APEX_050100.WWV_FLOW_DYNAMIC_EXEC", línea 935
ORA-06512: en "APEX_050100.WWV_FLOW_PLUGIN", línea 1328
error_statement:
begin declare

begin
wwv_flow_plugin_api.g_dynamic_action_ajax_result := IR_TO_MSEXCEL.ajax (p_dynamic_action => wwv_flow_plugin_api.g_dynamic_action,p_plugin => wwv_flow_plugin_api.g_plugin );end;
end;

**Comment by glebovpavel** [comment]
Hi José,

thank you for using this plugin.
Could you please give me a log like described in page 3 in Instructions.pdf?

P.S. Are you using the last version of packages? 

Regards,
Pavel

**Comment by srinuanne** [comment]
I am also facing the same issue.
Please provide me the solution if you have

**Comment by glebovpavel** [comment]
Should be fixed in 3.13 
Otherwise please reopen this issue

**Comment by shraddhapol** [comment]
hi, 
i am facing the similar issue.

Error in PLSQL code raised during plug-in processing.
Contact your application administrator.

Technical Info (only visible for developers)
is_internal_error: true
apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
ora_sqlcode: -20001
ora_sqlerrm: ORA-20001: ORA-21560: argument 3 is null, invalid, or out of range ORA-06512: at "SYS.DBMS_LOB", line 991 ORA-06512: at "HOU.IR_TO_XLSX", line 2137 ORA-06512: at "HOU.IR_TO_XLSX", line 2301 ORA-06512: at "HOU.IR_TO_MSEXCEL", line 330
component.type: APEX_APPLICATION_PAGE_DA_ACTS
component.id: 102814871124777745
component.name: PLUGIN_AT.FRT.GPV_IR_TO_MSEXCEL
error_backtrace:
ORA-06512: at "HOU.IR_TO_MSEXCEL", line 360
ORA-06512: at line 4
ORA-06512: at "SYS.DBMS_SQL", line 1707
ORA-06512: at "APEX_180200.WWV_FLOW_DYNAMIC_EXEC", line 2450
ORA-06512: at "APEX_180200.WWV_FLOW_DYNAMIC_EXEC", line 1476
ORA-06512: at "APEX_180200.WWV_FLOW_PLUGIN", line 1377

**Comment by wilyanresna** [comment]
I have this problem with version 3.24..
I have grant this :
- GRANT EXECUTE ON SYS.DBMS_LOB TO #USER#;
- GRANT EXECUTE ON SYS.UTL_FILE TO #USER#;
- GRANT EXECUTE ON IR_TO_MSEXCEL TO #USER#;
- GRANT EXECUTE ON IR_TO_XLSX TO #USER#;

But i always get "Error in PLSQL code raised during plug-in processing"

I want to try version 3.13, when can i get that version..?

**Comment by wilyanresna** [comment]
I have this problem with version 3.24..
I have grant this :
- GRANT EXECUTE ON SYS.DBMS_LOB TO #USER#;
- GRANT EXECUTE ON SYS.UTL_FILE TO #USER#;
- GRANT EXECUTE ON IR_TO_MSEXCEL TO #USER#;
- GRANT EXECUTE ON IR_TO_XLSX TO #USER#;

But i always get "Error in PLSQL code raised during plug-in processing"

I want to try version 3.13, when can i get that version..?
