### ISSUE TITLE
in IR_TO_MSEXCEL.ajax function missed branch: elsif p_download_type = 'M'

### ISSUE THREAD

**Issue by mpp2004** [glebovpavel/IR_to_MSExcel#32]
should be likely like in previous releases to support Moritz Klein commi235:
       --2017-12-29 missed code start
       elsif p_download_type = 'M' then -- use Moritz Klein engine https://github.com/commi235                         
       apexir_xlsx_pkg.download(  p_ir_region_id   => v_affected_region_id, 
                                  p_app_id         => apex_application.g_x01, 
                                  p_ir_page_id     => apex_application.g_x02 
                                ); 
     --2017-12-29 missed code end
      else
        raise_application_error(-20001,'Unknown download_type: '||p_download_type);
      end if;

**Comment by glebovpavel** [comment]
Fixed in 3.1
