### ISSUE TITLE
IR_TO_MSEXCEL : inconsistent datatypes: expected CHAR got BLOB 

### ISSUE THREAD

**Issue by mpp2004** [glebovpavel/IR_to_MSExcel#33]
For some specific IR I've got :
Error in PLSQL code raised during plug-in processing.

ORA-20001: ORA-00932: inconsistent datatypes: expected CHAR got BLOB ORA-06512: przy "SYS.DBMS_SQL", linia 1712 ORA-06512: przy "SER.IR_TO_XLSX", linia 1651 ORA-06512: przy "SER.IR_TO_XLSX", linia 1848 ORA-06512: przy "SER.IR_TO_XLSX", linia 2018 ORA-06512: przy "SER.IR_TO_MSEXCEL", linia 158

Technical Info (only visible for developers)1.is_internal_error: true
2.apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
3.ora_sqlcode: -20001
4.ora_sqlerrm: ORA-20001: ORA-00932: inconsistent datatypes: expected CHAR got BLOB ORA-06512: przy "SYS.DBMS_SQL", linia 1712 ORA-06512: przy "SER.IR_TO_XLSX", linia 1651 ORA-06512: przy "SER.IR_TO_XLSX", linia 1848 ORA-06512: przy "SER.IR_TO_XLSX", linia 2018 ORA-06512: przy "SER.IR_TO_MSEXCEL", linia 158
5.component.type: APEX_APPLICATION_PAGE_DA_ACTS
6.component.id: 74701456042284939
7.component.name: PLUGIN_AT.FRT.GPV_IR_TO_MSEXCEL
8.error_backtrace: ORA-06512: przy "SER.IR_TO_MSEXCEL", linia 186
ORA-06512: przy linia 4
ORA-06512: przy "SYS.DBMS_SYS_SQL", linia 2107
ORA-06512: przy "SYS.WWV_DBMS_SQL", linia 1033
ORA-06512: przy "SYS.WWV_DBMS_SQL", linia 1047
ORA-06512: przy "APEX_050000.WWV_FLOW_DYNAMIC_EXEC", linia 895
ORA-06512: przy "APEX_050000.WWV_FLOW_PLUGIN", linia 1209

9.error_statement: begin declare

begin
wwv_flow_plugin_api.g_dynamic_action_ajax_result := IR_TO_MSEXCEL.ajax (p_dynamic_action => wwv_flow_plugin_api.g_dynamic_action,p_plugin => wwv_flow_plugin_api.g_plugin );end;
end;

**Comment by glebovpavel** [comment]
Hi,
Thank you for using this plugin! 

Unfortunately support of BLOB - columns is not planned.
You can exclude BLOB - columns from download using 
not ir_to_msexcel.is_ir2msexcel
like described in documentation in "How to exclude report columns from export/make columns that are visible in Excel but not visible in Interactive Report (not for Interactive Grid)".

Regards,
Pavel

**Comment by mpp2004** [comment]
Thanks for explanation, I have tested it on some tables and views I have from couple of other databases accessed by dblink in APEX. I really dont know sometimes exact field types, it looks in some scenarios that there are long varchar fields that are treated by Oracle like clobs/blobs. IR itself does not support BLOB fields, so your solution - by definition - could not be better when applying to IR.   May be some other exports to XLSX would be possibile not from IR but directly from SQL / PL/SQL query/cursor or from Classic Report based on query/based on function or apex collection.   I used your plug-in more than 2 years ago in previous Apex version 5.0, for dumping in xlsx rather big tables (100 000+ rows, 1-10 KB per row), and I used &#39;M&#39;-switch to Mori Klein packages. In 12.2017 I  tested your new version, but I havent newest Apex (I have no need to migrate application to newest version of Apex), so I have to make some manual changes to new plugin import script to satisfy  import routine in  Apex 5.0 version I&#39;m using. Such backward incopatibility in new version import scripts (just after version change from 5.0 to 5.1) is one of things I hate (but it is of course not your fault, Oracle for some reason is doing this such  way).   Finally I found, that your new version is really better than previous one however applying to &#39;my&#39; tables Mori Klein is still winner in speed. So I stay with that and just copy from your new version to old one few lines of code that implement switching on/of columns to display or/and  to export as it is some additional functionality I can likely use.   Thanks a lot for your effort of implementing really missed by Oracle &#39;simple&#39; functionality of exporting IR to anything usefull  incuding XLSX format (formats built in APEX - csv, pdf, xls, html - are really poor implemented and in most practical cases I have seen are not to be accepted by the end user).  Best regards,  Marek Prokop 
                
              
               
                 
                  Dnia 8 stycznia 2018 14:00 Pavel Glebov &lt;notifications@github.com&gt; napisał(a):
                 
                 
                   Hi,  
Thank you for using this plugin! 
 Unfortunately support of BLOB - columns is not planned.  
You can exclude BLOB - columns from download using  
not ir_to_msexcel.is_ir2msexcel  
like described in documentation in &#34;How to exclude report columns from export/make columns that are visible in Excel but not visible in Interactive Report (not for Interactive Grid)&#34;. 
 Regards,  
Pavel

**Comment by glebovpavel** [comment]
Hi Marek,

thank you for detailed explanation. 
If in the future you will migrate to the APEX 5.1.3 or 5.2 -) you can additionally use download from Interactive Grid functionality of my plugin. 

Regards,
Pavel

**Comment by mpp2004** [comment]
Hi once again,  I finally traced source of the problem (using your XLSX plugin version for Apex 5.0) - may be interesting for you, however it is rather too rare/specific to open new issue on Github. But when it exists *in data* it may be very difficult to find out the origin -imagine you have 100000+ records to export with only few that causes the problem.   The problem may occur when text data contaminated by control characters like U+001F is used somewhere to feed xml file. Such characters are normally invisible on output device. Data may be &#39;infected&#39; when someone copy/paste &#39;text&#39; containing control characters to application, and entry routine does allow to input them without filtering.   To simulate and trigger such issue in IR I attached:     1_U001F_problem_SQL_EXAMPLE.tx    with SQL statement to define IR query. To see control characters you should open it e.g. with Notepad++. When you export IR based on this query, you obtain results according to method chosen. Outcomes are documented in attached files:   2_U001F_problem_MORITZ_KLEIN_X  3_U001F_problem_MORITZ_KLEIN_X  4_U001F_problem_APEX_PDF.pdf  5_U001F_problem_APEX_HTM.htm  6_U001F_problem_APEX_CSV.csv  7_U001F_problem_ERROR_PAVEL_GL   .htm and .csv are able to open correctly and they contain control characters in data while .xlsx and .pdf are not able to open, .zip is able to open and you can drill directory structure and xml files. Using your XLSX engine to process, it   prints error description including U+001F reason - to be seen in U001F_problem_ERROR_PAVEL_GLEB   I have not opportunity to check Oracle Apex standard xls export for such data.    Further description on source of this problem here:  www.w3.org www.w3.org   and info about this specific control character that I use in the example:  graphemica.com graphemica.com   Best regards  Marek Prokop  
                
              
               
                 
                  Dnia 9 stycznia 2018 12:43 Pavel Glebov &lt;notifications@github.com&gt; napisał(a):
                 
                 
                   Hi Marek, 
 thank you for detailed explanation.  
If in the future you will migrate to the APEX 5.1.3 or 5.2 -) you can additionally use download from Interactive Grid functionality of my plugin. 
 Regards,  
Pavel 

 —  You are receiving this because you authored the thread.  Reply to this email directly,  github.com view it on GitHub , or  github.com mute the thread .

Error in PLSQL code raised during plug-in processing.

ORA-20001: ORA-31011: Niepowodzenie analizy składniowej XML ORA-19213: wystąpił błąd podczas przetwarzania XML; wiersze: 6 LPX-00217: niepoprawny znak 31 (U+001F) ORA-06512: przy "SYS.XMLTYPE", linia 272 ORA-06512: przy "SER.IR_TO_XML", linia 1173 ORA-06512: przy "SER.XML_TO_XSLX", linia 849 ORA-06512: przy "SER.IR_TO_MSEXCEL", linia 141


Technical Info (only visible for developers)1.is_internal_error: true
2.apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
3.ora_sqlcode: -20001
4.ora_sqlerrm: ORA-20001: ORA-31011: Niepowodzenie analizy składniowej XML ORA-19213: wystąpił błąd podczas przetwarzania XML; wiersze: 6 LPX-00217: niepoprawny znak 31 (U+001F) ORA-06512: przy "SYS.XMLTYPE", linia 272 ORA-06512: przy "SER.IR_TO_XML", linia 1173 ORA-06512: przy "SER.XML_TO_XSLX", linia 849 ORA-06512: przy "SER.IR_TO_MSEXCEL", linia 141
5.component.type: APEX_APPLICATION_PAGE_DA_ACTS
6.component.id: 74701617017284941
7.component.name: PLUGIN_AT.FRT.GPV_IR_TO_MSEXCEL
8.error_backtrace: ORA-06512: przy "SER.IR_TO_MSEXCEL", linia 178
ORA-06512: przy linia 4
ORA-06512: przy "SYS.DBMS_SYS_SQL", linia 2107
ORA-06512: przy "SYS.WWV_DBMS_SQL", linia 1033
ORA-06512: przy "SYS.WWV_DBMS_SQL", linia 1047
ORA-06512: przy "APEX_050000.WWV_FLOW_DYNAMIC_EXEC", linia 895
ORA-06512: przy "APEX_050000.WWV_FLOW_PLUGIN", linia 1209


9.error_statement: begin declare

begin
wwv_flow_plugin_api.g_dynamic_action_ajax_result := IR_TO_MSEXCEL.ajax (p_dynamic_action => wwv_flow_plugin_api.g_dynamic_action,p_plugin => wwv_flow_plugin_api.g_plugin );end;
end;


select 'SomenameXYZ, 50 mg + 20mg x 30 pcs.' AS x from DUAL

**Comment by mpp2004** [comment]
... continuing study of specific/rare U+001F problem:   I opened csv (generated from U+001F sample IR mentioned in my previous email, and exported by standard Apex csv export) in MS Excel 2016 (32 bit  Win7 64 PL) and then saved it from Excel as xlsx (see attached source .csv and resulted .xlsx and .zip). Such xlsx opens correctly in MS Excel and preserves U+001F, so I investigate how Microsoft is able to handle it. You can see Anthon Shaffer / Microsoft difference in attached .png screenshoot. This difference makes Moritz Klein generated file to be not usable (and your engine when consuming U+001F just  blows out somewhere giving hint what it does not digest). It shows  the direction to satisfy Microsoft living standards.   Best regards   Marek Prokop

**Comment by glebovpavel** [comment]
Hi Marek,

tank you for finding this issue. I understand, how difficult  was find the right case. 
That  was a real help!
I try to make a fix in the next few days.

Regards,
Pavel
