### ISSUE TITLE
Error on downloading

### ISSUE THREAD

**Issue by DanielUpbase** [glebovpavel/IR_to_MSExcel#34]
In my develop environment (Windows) no problem but in production (Linux) I get this error. V. 2.21

Any idea what is the problem?

Thanks DJ   

Error in PLSQL code raised during plug-in processing.

ORA-20001: ORA-06508: PL/SQL: could not find program unit being called ORA-06512: at "XXXXXX_001.IR_TO_XLSX", line 2036 ORA-06512: at "XXXXXXX_001.IR_TO_MSEXCEL", line 158

Technical Info (only visible for developers)

is_internal_error: true
apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
ora_sqlcode: -20001
ora_sqlerrm: ORA-20001: ORA-06508: PL/SQL: could not find program unit being called ORA-06512: at "XXXXX_001.IR_TO_XLSX", line 2036 ORA-06512: at "XXXXXX_001.IR_TO_MSEXCEL", line 158
component.type: APEX_APPLICATION_PAGE_DA_ACTS
component.id: 2099264664948921
component.name: PLUGIN_AT.FRT.GPV_IR_TO_MSEXCEL
error_backtrace:
ORA-06512: at "XXXXXX_001.IR_TO_MSEXCEL", line 179
ORA-06512: at line 4
ORA-06512: at "SYS.DBMS_SQL", line 1825
ORA-06512: at "APEX_050100.WWV_FLOW_DYNAMIC_EXEC", line 1880
ORA-06512: at "APEX_050100.WWV_FLOW_DYNAMIC_EXEC", line 1895
ORA-06512: at "APEX_050100.WWV_FLOW_DYNAMIC_EXEC", line 936
ORA-06512: at "APEX_050100.WWV_FLOW_PLUGIN", line 1330
error_statement:
begin declare

begin
wwv_flow_plugin_api.g_dynamic_action_ajax_result := IR_TO_MSEXCEL.ajax (p_dynamic_action => wwv_flow_plugin_api.g_dynamic_action,p_plugin => wwv_flow_plugin_api.g_plugin );end;
end;

**Comment by glebovpavel** [comment]
Hi Daniel,

could you please try to grant

GRANT EXECUTE ON SYS.DBMS_LOB TO #USER#;

Where #USER# should be replaced to APEX Application Parsing Schema.

Regards,
Pavel

**Comment by DanielUpbase** [comment]
Hi Pavel 

Fond out that GRANT is the problem by running this sql: 
SELECT * FROM all_tab_privs WHERE grantee = 'PUBLIC' AND table_name = 'UTL_FILE';

I have not privileges to run you CRANT. Will DBA do it next week and I'll let you to know if it works.

Thanks for your help /DJ

**Comment by glebovpavel** [comment]
I add this case in documentation
