### ISSUE TITLE
Invalid Cursor

### ISSUE THREAD

**Issue by BirtheG** [glebovpavel/IR_to_MSExcel#41]
Hi Pavel,
thanks for the very useful plugin.
I have installed the plugin on two XE Apex 5.1.4 pc's. At both PC I get an error because of the cursors in the package:
`- additional_info: ORA-20001: ORA-01001: invalid cursor
ORA-06512: at &quot;TEST.IR_TO_MSEXCEL&quot;, line 284
ORA-06512: at &quot;TEST.IR_TO_MSEXCEL&quot;, line 304`

Do you have idea, how I can fix it?.

Many thanks.

Birthe

**Comment by glebovpavel** [comment]
Should be fixed in 3.13

**Comment by BirtheG** [comment]
Thank you Pavel. 

The error is not shown. 

Birthe
