### ISSUE TITLE
Export IG Values with dates -> Application Primary Language Issue

### ISSUE THREAD

**Issue by BirtheG** [glebovpavel/IR_to_MSExcel#42]
Halle,

If I have an IG with dates in , I got an error from moment-with-locales.js

> Uncaught TypeError: Cannot read property 'preparse' of null
    at ce (moment-with-locales.js:1)
    at moment-with-locales.js:1
    at Ye (moment-with-locales.js:1)
    at ye (moment-with-locales.js:1)
    at e (moment-with-locales.js:1)
    at getCellDate (IG2MSEXCEL.js:42)
    at getWorksheet (IG2MSEXCEL.js:237)
    at buildExcel (IG2MSEXCEL.js:443)
    at IG2MSEXCEL.js:337
    at Object.execCb (require.js?v=5.1.4.00.08:29)

My NLS_Lang settings are :
>LANGUAGE	GERMAN
TERRITORY	GERMANY
CHARACTER SET	AL32UTF8

Do you know, how to solve the issue?

Many thanks.

Birthe

**Comment by BirtheG** [comment]
Hello,

I have made some more test and can reproduce the bug.

The problem belongs to the Oracle Apex Application Primary Language.
If I am using English(en) the XLS export works  fine with date values. But if I change to German(de) the XLS Export raises the error.

Please could you check the localisation in the moment-with-locales.js file.

Thanks.

Birthe

**Comment by glebovpavel** [comment]
Bug: false recognition of NLS-settings

**Comment by glebovpavel** [comment]
@BirtheG  Fixed in v.3.12

**Comment by BirtheG** [comment]
Thank you Pavel.
It works fine with DE NLS.

Birthe
