### ISSUE TITLE
ORA-01489: result of string concatenation is too long

### ISSUE THREAD

**Issue by gierasm** [glebovpavel/IR_to_MSExcel#43]
I can't get the Excel spreadsheet to come up.  I keep getting the following message:

![error_message](https://user-images.githubusercontent.com/38768315/39330082-07d2c2f4-4990-11e8-8a91-fbd2108a14ca.PNG)

I have 16 columns that I am trying to download into that spreadsheet.  They columns contain random datatypes. 

If I need to provide any other info just let me know.  Thanks for any help you can provide. 

Susan

**Comment by glebovpavel** [comment]
Hi Susan, 

thank you for using this plugin. 
If you use APEX items as bind variables in your Interactive Report please check that these items have a names less 30 bytes.  That should help. 

Regards,
Pavel
