### ISSUE TITLE
IG: Export Date with NLS-LANG DE

### ISSUE THREAD

**Issue by BirtheG** [glebovpavel/IR_to_MSExcel#46]
Hallo Pavel,
The export with NLS-Lang German works well now.
I have found a probelem with the date. The excel export date is one day less then it is in APEX.
Example: 26.05.2018
Excel: 25.05.2018 23:00
Please could you have a look into it.

Many thanks for your help.

Birthe

**Comment by BirtheG** [comment]
Hallo Pavel,

I think, I have solve the issue. The issue belongs to the calculation and the return of float value.

I have changed the line 49 in IG2MSEXCEL.JS from
cell.v = ((parsedDate.toDate() - epoch) / (24 * 60 * 60 * 1000))+1 ;	// + 1 because excel leap bug
to
cell.v = **Math.ceil(**((parsedDate.toDate() - epoch) / (24 * 60 * 60 * 1000))+1 **)** ;  // + 1 because excel leap bug

The result gives now an integer instead of a float.

Please could you check, if the solution works on your side too.

Many thanks,

Birthe

**Comment by glebovpavel** [comment]
Hi Birthe,

thank you!

I released v.3.14, bug should be fixed now.

Regards,
Pavel
