### ISSUE TITLE
Incorrect result exporting numbers with formatting

### ISSUE THREAD

**Issue by p3t3r** [glebovpavel/IR_to_MSExcel#48]
IG grid export: Formatting with for example thousand separator doesn't work.

Problem is in the function getCellNumber:
_str.replace(re, ""); //remove all symbols except digits and decimalSeparator_	
should be
_str = str.replace(re, ""); //remove all symbols except digits and decimalSeparator_	

Additional question:
Is it possible to keep the formatting in Excel for numbers? 
For example:
555,30 becomens 555,3 in Excel
I want to keep to trailing zero.

**Comment by glebovpavel** [comment]
@p3t3r Hm, should be fixed in last bugfix https://github.com/glebovpavel/IR_to_MSExcel/commit/bb0bcec2e532e58596670ca36b6144dc26cf51db
