### ISSUE TITLE
Trouble getting excel icon in APEX 18.1

### ISSUE THREAD

**Issue by CarrieMJ** [glebovpavel/IR_to_MSExcel#49]
Has this been updated for 18.1?  I followed your instructions exactly and can see PDF as a download option in my interactive report (which wasn't there before i installed the plug-in), but i can't see an XLS option or the RTF option, which also seems to have been included in the plug-in. 

![image](https://user-images.githubusercontent.com/29610250/43141867-000277e2-8f25-11e8-82e8-63bc932e39ef.png)
![image](https://user-images.githubusercontent.com/29610250/43141893-13c29168-8f25-11e8-82aa-19f97b43a469.png)

**Comment by glebovpavel** [comment]
Hm, should works on 18.1 - see demo
https://apex.oracle.com/pls/apex/f?p=35446:1

do you have any javascript errors?

P.S. Your modal page looks different comparing to the  apex.oracle.com
![image](https://user-images.githubusercontent.com/7167118/43142831-966acc32-8f59-11e8-9142-a29116bfce2b.png)
- cross on the top right, colors. Do you using any modifications/custom templates? 

Regards,
Pavel

**Comment by CarrieMJ** [comment]
No, i don't have a custom template. It's possible we have an unsupported one - we upgraded from a VERY old version of APEX straight to 18.1. I'm not sure if that makes a difference. I also don't get any errors at all. I followed your instructions to add an independent button to call the download. When i press the button it doesn't do anything at all.

**Comment by j156580801** [comment]
I install a new apex 18.1，and I still can not show xlsx icon。

Java scripts console show this error:
      ReferenceError: excel_gpv is not defined.

Regards，
Joe

**Comment by j156580801** [comment]
![image](https://user-images.githubusercontent.com/39396801/44975376-d813d880-af94-11e8-9cbb-9de0565faf21.png)

**Comment by j156580801** [comment]
Java scripts console log：

指向“http://ebsapex.oracle.com:8080/ords/joe_workspace/r/102/files/plugin/53723757907268895806/v64/IR2MSEXCEL.js”的 <script> 加载失败。 f:170
Custom Elements: `Element#attachShadow` was not patched. jetCommonBundle.min.js:39:12704
jQuery.Deferred exception: excel_gpv is not defined @http://ebsapex.oracle.com:8080/ords/f?p=102:3:10955605431996::::::194:13
@http://ebsapex.oracle.com:8080/ords/f?p=102:3:10955605431996::::::194:2
i@http://ebsapex.oracle.com:8080/i/libraries/apex/minified/desktop_all.min.js?v=18.1.0.00.45:2:27978
add@http://ebsapex.oracle.com:8080/i/libraries/apex/minified/desktop_all.min.js?v=18.1.0.00.45:2:28282
@http://ebsapex.oracle.com:8080/ords/f?p=102:3:10955605431996::::::190:1
a.init@http://ebsapex.oracle.com:8080/i/libraries/apex/minified/desktop_all.min.js?v=18.1.0.00.45:16:5303
@http://ebsapex.oracle.com:8080/ords/f?p=102:3:10955605431996::::::188:1
j@http://ebsapex.oracle.com:8080/i/libraries/apex/minified/desktop_all.min.js?v=18.1.0.00.45:2:29946
g/</k<@http://ebsapex.oracle.com:8080/i/libraries/apex/minified/desktop_all.min.js?v=18.1.0.00.45:2:30262
 undefined desktop_all.min.js:2:31515
[显示/隐藏消息细节。] ReferenceError: excel_gpv is not defined[详细了解] f:194:13
<匿名>
http://ebsapex.oracle.com:8080/ords/f:194:13
<匿名>
http://ebsapex.oracle.com:8080/ords/f:194:2
i
http://ebsapex.oracle.com:8080/i/libraries/apex/minified/desktop_all.min.js:2:27978
add
http://ebsapex.oracle.com:8080/i/libraries/apex/minified/desktop_all.min.js:2:28282
<匿名>
http://ebsapex.oracle.com:8080/ords/f:190:1
a.init
http://ebsapex.oracle.com:8080/i/libraries/apex/minified/desktop_all.min.js:16:5303
<匿名>
http://ebsapex.oracle.com:8080/ords/f:188:1
j
http://ebsapex.oracle.com:8080/i/libraries/apex/minified/desktop_all.min.js:2:29946
g/</k<
http://ebsapex.oracle.com:8080/i/libraries/apex/minified/desktop_all.min.js:2:30262

**Comment by glebovpavel** [comment]
Icon is moved into Download dialog in v.3.15
