### ISSUE TITLE
Not able to download interactive Grid as xlsx

### ISSUE THREAD

**Issue by abha3011** [glebovpavel/IR_to_MSExcel#54]
Hello,

Thanks a lot for this plugin.
I am using this plugin to download the interactive grid in an excel. But I do not get the xlsx button under the Actions-->Download menu. I get the button outside on top of the interactive grid. Wnd when I click on that button , it gives me an error saying : "Error in PLSQL code raised during plug-in processing."

![ig error](https://user-images.githubusercontent.com/41986983/47219850-4af3da00-d3b0-11e8-8b9a-c281f2ba11b9.PNG)

Although, If I create an interactive report instead of Interactive grid, I get the proper icon to download the excel, and it gets downloaded properly.

Can you please suggest, if there is something extra I need to do in case of interactive grid. My APEX version is 18.

Regrds,
Abha..

**Comment by abha3011** [comment]
Hi Pavel,

Can you please help me regarding this issue. In the debug, it says "Invalid cursor " as well. Can you please suggest what needs to be done. Please find below the screenshot of the debug page which specifies the error is detail .
![image](https://user-images.githubusercontent.com/41986983/47281531-ddc48c80-d5db-11e8-9c45-e3f087861bf3.png)

Looking forward for your reply.

Regards,
Abha

**Comment by abha3011** [comment]
Hi, 
I have resolved the problem by adding if cursor open clause in procedure :  'print_column_properties_json' as:

    if l_columns_cursor%ISOPEN then
     close l_columns_cursor;
    END IF;
    If l_highlihts_cursor%ISOPEN then
     close l_highlihts_cursor;
    END IF;
      
After this I am able to download the report from the XLSX button that is present on the toolbar of the interactive grid. The icon still doesn't appear in the Actions --> Download options. But I think I am ok with the button on  the toolbar.

Please let me know, if this resolution is ok and will not affect any other functionality.

Regards,
Abha

**Comment by abha3011** [comment]
It is working fine for me...so closing the issue.

**Comment by glebovpavel** [comment]
Hi Abha, 

Do i right understand, that nothing should be changed in IR_TO_MSEXCEL.pkb because strings listed in your message above was added in #42 ?

Regards,
Pavel

**Comment by abha3011** [comment]
Hi Pavel,

I recently (19th Oct) downloaded the plugin and this string was missing at that time so I needed to add it in the package "IR_TO_MSEXCEL.pkb", as it was throwing the error. If it is already there now, I think nothing needs to be changed anymore.

Thanks,
Abha..
