### ISSUE TITLE
Issue of javascript item not found

### ISSUE THREAD

**Issue by TonyCMiller** [glebovpavel/IR_to_MSExcel#58]
Install in APEX 18.2g an issue with your plugin on a hosted instance of APEX 18.2.  When I install and use on a page, when I run the page I am getting following javascript errors:

![image](https://user-images.githubusercontent.com/14878234/55170196-bd28d180-513b-11e9-80b2-6c809f2c645e.png)

Can you offer any assistance?

tony miller
Texas.Apex.Developer@Gmail.com

**Comment by glebovpavel** [comment]
Should works for 18.2 (at least I have tested it on my VM)
