### ISSUE TITLE
APEX 19.1 Icon is not the same as standard icons

### ISSUE THREAD

**Issue by TonyCMiller** [glebovpavel/IR_to_MSExcel#59]
Testing in 18.2 and also 19.1 the icon is not the same as standard icons and also misplaced in display:

![image](https://user-images.githubusercontent.com/14878234/55171381-df235380-513d-11e9-8c4c-83eab6c96d87.png)

Can this be corrected?  

Thank you,

Tiny Miller
Texas.Apex.Developer@gmail.com

**Comment by glebovpavel** [comment]
In plugin-version 3.21 icon should be the same.
