### ISSUE TITLE
ORA-01422

### ISSUE THREAD

**Issue by DragicevicD** [glebovpavel/IR_to_MSExcel#64]
I am having the next issue with this plugin: http://prntscr.com/pj2cxt

This error is happening only sometimes. Any ideas why?

**Comment by glebovpavel** [comment]
Do you have the same pade in different browser tabs? (Only idea...)

**Comment by DragicevicD** [comment]
No. I have tried that though to try to cause the problem.

**Comment by glebovpavel** [comment]
Fixed in 3.20
