### ISSUE TITLE
Invalid Excel file when downloading from IG

### ISSUE THREAD

**Issue by vadimbv** [glebovpavel/IR_to_MSExcel#65]
Hello, Pavel!
Thank you for a very useful plugin. 
But sometimes (on one enviroment - occasionally, on another environment - always) it does not make a valid xlsx file while downloading the IG contents. 
I press the 'xlsx' button - for a moment opens a new tab in IE then I get a standard option to download the file - but it is not hte excel one. It looks like a csv without any delimiters :( 
Pls see the attachment (I hope cyrillic symbols won't confuse you).
[report.xlsx](https://github.com/glebovpavel/IR_to_MSExcel/files/3787371/report.xlsx)

Also I modified your IG2MSEXCEL.js file - see the addDownloadXLSXiconToIG function to add the xlsx icon "stylishly". It works in APEX 5.1 - I don't have any other versions now. If you can modify for other versions - I'll be glad because I'm not good at js.
[IG2MSEXCEL.txt](https://github.com/glebovpavel/IR_to_MSExcel/files/3787387/IG2MSEXCEL.txt)

This behaviour is in version 3.16 of the plugin. It has no deal to my modification of IG2MSEXCEL - in your file "out of the box" the behaviour is the same. 
In the plugin version 3.0 everything is working correctly.

**Comment by glebovpavel** [comment]
Hi Vadim, 

thanks you for you real important contribution. I'm trying to collect VM for all APEX versions starting 5.1, and, I hope, the next version will be completely adopted and tested for all supportd version of APEX. 
P.S. Try to migrate at least to 19.1, it's stable in production and is much more comfortable for developers -)). 

Regards,
Pavel

**Comment by glebovpavel** [comment]
There are small changes in UI for starting dowload IG in the new version, 3.21. 
So, problem can be fixed.
