### ISSUE TITLE
APEX 19.2 compatible

### ISSUE THREAD

**Issue by jporrata1** [glebovpavel/IR_to_MSExcel#67]
Hi,

Is this plugin compatible with version 19.2.
Am trying to use it but having an error.
What is the latest version?

Thanks
Javier

**Comment by glebovpavel** [comment]
Hm, i did't adapted plugin for 19.2, but it works on https://apex.oracle.com/pls/apex/f?p=35446:1:::::: without any changes.
Do you have the last version from https://github.com/glebovpavel/IR_to_MSExcel/archive/master.zip ?

**Comment by jporrata1** [comment]
Hi Pavel,

Thanks for your reply,
I will try this version and let  you know.

The one I have give this error


[image: Capture.JPG]

Thanks again!

**Comment by jporrata1** [comment]
Hi Pavel,

Still having the same error with the one you sent.

Do you have any suggestion of how to fix this?

I will appreciate your help!

Thanks

**Comment by jporrata1** [comment]
This is the error:

Error in PLSQL code raised during plug-in processing.
Contact your application administrator.

Technical Info (only visible for developers)
is_internal_error: true
apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
ora_sqlcode: -20001
ora_sqlerrm: ORA-20001: ORA-06508: PL/SQL: could not find program unit being called ORA-06512: at "RISKMANDEV.IR_TO_XLSX", line 2118 ORA-06512: at "RISKMANDEV.IR_TO_MSEXCEL", line 306
component.type: APEX_APPLICATION_PAGE_DA_ACTS
component.id: 5988492202630838
component.name: PLUGIN_AT.FRT.GPV_IR_TO_MSEXCEL
error_backtrace:
ORA-06512: at "RISKMANDEV.IR_TO_MSEXCEL", line 336
ORA-06512: at line 4
ORA-06512: at "SYS.DBMS_SYS_SQL", line 1926
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_190200", line 601
ORA-06512: at "APEX_190200.WWV_FLOW_DYNAMIC_EXEC", line 2550
ORA-06512: at "APEX_190200.WWV_FLOW_DYNAMIC_EXEC", line 1524
ORA-06512: at "APEX_190200.WWV_FLOW_PLUGIN", line 1493
error_statement:
begin declare

begin
wwv_flow_plugin_api.g_dynamic_action_ajax_result := IR_TO_MSEXCEL.ajax (p_dynamic_action => wwv_flow_plugin_api.g_dynamic_action,p_plugin => wwv_flow_plugin_api.g_plugin );end;
end;

**Comment by glebovpavel** [comment]
Hi, could you please check that the required grants to dbms_lob and utl_file -  packages are given like described in Instructions.pdf on page 6 (bottom)?

**Comment by jporrata1** [comment]
Thanks Pavel for you reply!

This is a very useful plugin!!!   Great job!

**Comment by glebovpavel** [comment]
Documentation updated in 3.21.
+ Tested for 19.2

**Comment by jporrata1** [comment]
Hi Pavel,

Hope you're fine!

Can I place report headers using the Interactive Report to Excel plugin?
I need to export some reports but I need to include some Report Headers on
them.

Is it possible?
I saw that one user in the forum menction something about customize the
PL/SQL Api.
https://forums.oracle.com/ords/apexds/post/report-header-missing-in-download-to-excel-or-pdf-column-or-3602

Can this be done?

Thanks for the help!
Javier
