### ISSUE TITLE
No download icon for Interactive Grid in Apex 19.1

### ISSUE THREAD

**Issue by katajs** [glebovpavel/IR_to_MSExcel#68]
Hi Pavel,

Followed all the install/setup steps, but no download icon shows up for Interactive Grid (Oracle Apex 19.1).
![image](https://user-images.githubusercontent.com/50468270/69095662-6ba9bb80-0a18-11ea-9bcd-7f03b982ce3c.png)

Just to point out, unlike IR there is no XLS download option for IG to check. 

Any ideas on the causes?

Thank you.

**Comment by jporrata1** [comment]
What version of Apex are you using?  Does it work in the IR?

**Comment by katajs** [comment]
Apex version is 19.1. And yes, it does work in IR on desktop (does not work on mobile ios in my case, but that is a different issue). 

Thank you.

**Comment by jporrata1** [comment]
Can you share the package you installed?  Am trying to use it in 19.2 but having an error when creating the file.   Am not sure am using the right file.   I also followed the video instructions.   Is there anything that you do additional to that?

Thanks for your help

**Comment by jporrata1** [comment]
Something weird is that the package I have only runs 8 statements when in the video shows 10 statements ran.

**Comment by katajs** [comment]
Hi Jporrata!

Initially, I made a mistake downloading from apex.world. Apex.world version is stale. Use http://glebovpavel.github.io/Description_IR_TO_XSLX/

It worked for me. Thank you.

**Comment by jporrata1** [comment]
Hi katajs,

I tried with that version but no luck.  Still have the same problem. Still  running 8 statements.
But thanks for your help!!!

**Comment by glebovpavel** [comment]
Please try the new version 3.21
