### ISSUE TITLE
Error when there are hidden computed columns 

### ISSUE THREAD

**Issue by mrpele** [glebovpavel/IR_to_MSExcel#70]
![error](https://user-images.githubusercontent.com/43929111/72789140-2dad5b80-3c44-11ea-8cde-4502e785d365.png)
![Adsız2](https://user-images.githubusercontent.com/43929111/72789145-30a84c00-3c44-11ea-803a-03eaa75ff1fa.png)
I have this error when i try to download it.. If i set computed columns visible, then it works...

**Comment by glebovpavel** [comment]
Thank you for finding  a bug. Fixed in 3.21
