### ISSUE TITLE
Fontstyling has changed for IR

### ISSUE THREAD

**Issue by ma-schroeder** [glebovpavel/IR_to_MSExcel#71]
Hi Pavel,

just updated to new version 3.22 and now the fontcolor of all data-rows in an Interactive Report (IR) changed to blue and styling is "underlined" now?

![ir_excel_styling2](https://user-images.githubusercontent.com/11662301/73084239-e5ed3500-3ecc-11ea-9ed8-9890950c97a0.jpg)

In a IGrid it seems to be OK with black and normal style though. Tested it on apex.oracle.com with APEX 19.2 and local with 19.1

**Comment by glebovpavel** [comment]
Fixed in 3.23
