### ISSUE TITLE
ora_sqlerrm: ORA-20001: Version:3.24 ORA-06502: PL/SQL: numeric or value error

### ISSUE THREAD

**Issue by Nikhith9999** [glebovpavel/IR_to_MSExcel#73]
Hi, 
I am getting an issue while using IR_TO_MSEXCEL 3.24 version for one of Interactive Grids, it works for few of them, but it shows the below error for few, I want to understand what are the usual case where this issue occurs

- ora_sqlerrm: ORA-20001: Version:3.24 ORA-06502: PL/SQL: numeric or value error
ORA-06512: at "IR_TO_MSEXCEL", line 332 < sys.htp.p(apex_json.get_clob_output); >
ORA-06512: at "IR_TO_MSEXCEL", line 357 < print_column_properties_json(p_application_id => apex_application.g_x02, >

**Comment by glebovpavel** [comment]
I think it happens in sys.htp.p(apex_json.get_clob_output);
I found the same problem here 
https://github.com/Pretius/apex-nested-reports/issues/7
Will be fixed in next version

**Comment by glebovpavel** [comment]
Fixed in 3.25
