### ISSUE TITLE
ORA-01403: no data found

### ISSUE THREAD

**Issue by gomanuke** [glebovpavel/IR_to_MSExcel#75]
Инсталляция plug-in (front-end части) текущей версии оканчивается сообщением об ошибке. 

Error installing plug-in.
ORA-01403: no data found
 UserADMIN  PARSING_SCHEME_NAME  en
Copyright © 1999, 2019, Oracle. All rights reserved.
Application Express 19.2.0.00.18

**Comment by glebovpavel** [comment]
Хм, попробовал на 
apex.oracle.com, 

Shared Components-> Plug-ins->Import

![image](https://user-images.githubusercontent.com/7167118/82118302-a8136580-9776-11ea-8a9b-0bf2e944a6fe.png)
![image](https://user-images.githubusercontent.com/7167118/82118324-cd07d880-9776-11ea-808f-de797aba7f0c.png)
Установилось без проблем. 

19.2 Сейчас не могу попробовать ....

**Comment by gomanuke** [comment]
Плугин таки установился, несмотря на ошибку. Закрываем тикет.
