### ISSUE TITLE
error on download

### ISSUE THREAD

**Issue by ahmed50736** [glebovpavel/IR_to_MSExcel#76]
ora_sqlerrm: ORA-20001: Version:3.24 ORA-20001: get_query_column_list: ORA-00942: table or view does not exist ORA-06512: at "RECYCLING.IR_TO_XLSX", line 973 < raise_application_error(-20001,'get_query_column_list: '||sqlerrm); > ORA-06512: at "RECYCLING.IR_TO_XLSX", line 1028 < v_query_column_list := get_query_column_list; > ORA-06512: at "RECYCLING.IR_TO_XLSX", line 2114 < init_t_report(p_app_id,p_page_id,p_region_id); > ORA-06512: at "RECYCLING.IR_TO_XLSX", line 2243 < get_report(p_app_id, > ORA-06512: at "RECYCLING.IR_TO_MSEXCEL", line 377 ORA-06512: at "APEX_190200.WWV_FLOW_DYNAMIC_EXEC", line 1524 ORA-06512: at "APEX_190200.WWV_FLOW_DYNAMIC_EXEC", line 2578 ORA-06512: at "RECYCLING.IR_TO_MSEXCEL", line 389 ORA-06512: at line 4 ORA-06512: at "SYS.DBMS_SYS_SQL", line 2120 ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_190200", line 601 ORA-06512: at "APEX_190200.WWV_FLOW_DYNAMIC_EXEC", line 2550 ORA-06512: at "APEX_190200.WWV_FLOW_DYNAMIC_EXEC", line 1499
component.type: APEX_APPLICATION_PAGE_DA_ACTS
component.id: 15639516340443302
component.name: PLUGIN_AT.FRT.GPV_IR_TO_MSEXCEL

**Comment by ahmed50736** [comment]
How can i solve it

**Comment by glebovpavel** [comment]
Very unusual error. 
Looks like some table are not available for Parsing Schema. Pay attention, that plugin-packages are using "AUTHID current_user"  statement, that means Parsing Schema can differs from "RECYCLING".
Anyway, please try "Parsing Schema"  section in documentation.

**Comment by ahmed50736** [comment]
Thank you, I solved it.
The Cause of the problem was that I was trying to export the excel sheet on report contain data from a web source -not local data-.

**Comment by glebovpavel** [comment]
@ahmed50736 Thank you for reporting a reason!
