### ISSUE TITLE
ORA-01007 when generating an excel file from IR

### ISSUE THREAD

**Issue by ThomasCarltonInPerson** [glebovpavel/IR_to_MSExcel#92]
Hi everyone,

I installed the plugin however I'm getting the error : ORA-01007 when generating the excel file. 

Here is what happens :

- When clicking generate an excel file from the IR, there is a redirection to domain.com/wwv_flow.show?p_flow_id=...
- The first time it redirects, it fails and the error ORA-01007 is raised
- However if I refresh the page (that has the url /wwv_flow.show?p_flow_id=...) by hitting F5, the excel file is generated 

It seems like there is an initialization issue.

Can anyone help please ?

Thank you in advance.

The error is raised in the package **IR_TO_XLSX**, procedure **generate_from_report**  and fires even when there are only two rows and one columne.

`    log('<<define_columns>>');    
    FOR i IN 1..v_colls_count LOOP
       log('define column '||i);
       log('column type '||l_report.desc_tab(i).col_type);      
       IF l_report.column_data_types(i) = 'DATE' THEN   
         dbms_sql.define_column(v_cur, i, v_date_dummy);         
       ELSIF l_report.column_data_types(i) = 'NUMBER' THEN   
         dbms_sql.define_column(v_cur, i, v_number_dummy);         
       ELSE --STRING
         dbms_sql.define_column(v_cur, i, v_char_dummy,32767);         <<<<<< Here
       END IF;         
    END LOOP define_columns; `

**Comment by glebovpavel** [comment]
Fixed in 3.26
