### ISSUE TITLE
APEX 20.2 upgrade error

### ISSUE THREAD

**Issue by omarsawalhah** [glebovpavel/IR_to_MSExcel#93]
I have upgraded my instance to 20.2, now I am having this error.
apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
ora_sqlcode: -6502
ora_sqlerrm: ORA-06502: PL/SQL: numeric or value error: character string buffer too small ORA-06512: at "APEX_200200.WWV_FLOW_CODE_EXEC_PLSQL", line 124 ORA-06512: at "APEX_200200.WWV_FLOW_DYNAMIC_EXEC", line 2282 ORA-06512: at "IR_TO_MSEXCEL", line 177 ORA-06512: at line 4 ORA-06512: at "SYS.DBMS_SYS_SQL", line 2120 ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_200200", line 635 ORA-06512: at "APEX_200200.WWV_FLOW_DYNAMIC_EXEC", line 2243 ORA-06512: at "APEX_200200.WWV_FLOW_CODE_EXEC_PLSQL", line 96 ORA-06512: at "APEX_200200.WWV_FLOW_CODE_EXEC_PLSQL", line 301 ORA-06512: at "APEX_200200.WWV_FLOW_CODE_EXEC", line 340

**Comment by omarsawalhah** [comment]
I found the error, the following line in function "render"
    v_plugin_id := apex_plugin.get_ajax_identifier;
I just increased the size of the variable  from 100 to 300
v_plugin_id                VARCHAR2(300);

Regards,
Omar

**Comment by glebovpavel** [comment]
Hi Omar, thank you!

i would fix this issue and some other bugs in the next release, but first I would test it ij the envirement. I hope, the result would be good-)

Regards,
Pavel

**Comment by glebovpavel** [comment]
Fixed in v 3.26
